# Generated by Django 3.2.16 on 2022-12-16 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SSITS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff_leave_report',
            name='staff_id',
        ),
        migrations.AddField(
            model_name='staff_leave_report',
            name='subject_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SSITS.subject'),
        ),
    ]
